### ISSUE TITLE
Call to undefined method League\Flysystem\Filesystem::getAdapter()

### ISSUE THREAD

**Issue by phpust** [Laravel-Backpack/BackupManager#100]
# Bug report

hi, i am running backpack 5 on laravel 9. there is a problem with this package and obviously it is not from spatie. 

### What I did:
after going to backups page in admin panel i get an error with this title ( **"Call to undefined method League\Flysystem\Filesystem::getAdapter()"** )

### What I expected to happen:

look like problem is from -> https://github.com/Laravel-Backpack/BackupManager/blob/4c1878c4edfd37c0d2aa0adbe81add9dcb56d274/src/app/Http/Controllers/BackupController.php#L26

``

### What happened:

it try to get driver letter and calling  getAdapter on it.           
$adapter = $disk->getDriver()->getAdapter();

### What I've already tried to fix it:

look like getDriver() is redundant and must be removed, final code will look like this:
`$adapter = $disk->getAdapter();`

### Backpack, Laravel, PHP, DB version:
BackPack 5 
Laravel 9.0

**Comment by phpust** [comment]
the full error is currently shown in this link : https://flareapp.io/share/87nzy167#F52

**Comment by tabacitu** [comment]
Thank you @phpust and sorry for leaving this unattended for so long. It's now fixed in #102 which will fix this and a few more things. It'll be merged in a few days.

Thank you for your patience! 🙏
