### ISSUE TITLE
Page title is non translated:  <title>backupmanager::backups :: 

### ISSUE THREAD

**Issue by dandarie** [Laravel-Backpack/BackupManager#114]
# Bug report

### What I did:

Installed BackupManager.

### What happened:

Page title wasn't translated.

### What I've already tried to fix it:

In [src\Http\Controllers\BackupController#52](https://github.com/Laravel-Backpack/BackupManager/blob/d4f5506e1509fca04e62fc7caeb4fb7cf0754d55/src/app/Http/Controllers/BackupController.php#L52):

`$this->data['title'] = trans('backpack::backup.backups');`

### Backpack, Laravel, PHP, DB version:
Backpack: 5.3.0
Laravel: 9.23
PHP: 8.1.3

**Comment by tabacitu** [comment]
Oups. Thanks @dandarie ! Closing in favor of https://github.com/Laravel-Backpack/BackupManager/pull/115
