### ISSUE TITLE
composer require backpack/backupmanager failed

### ISSUE THREAD

**Issue by mcfaith9** [Laravel-Backpack/BackupManager#117]
# Bug report

### What happened:

  Problem 1
    - backpack/backupmanager[v4.0.0, ..., v4.0.1] require spatie/laravel-backup ^8.0 -> satisfiable by spatie/laravel-backup[8.0.0, ..., v8.x-dev].
    - spatie/laravel-backup[8.0.0, ..., v8.x-dev] require illuminate/console ^9.0 -> found illuminate/console[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - spatie/laravel-backup[8.1.6, ..., 8.1.7] require illuminate/console ^9.0|^10.0 -> found illuminate/console[v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires backpack/backupmanager ^4.0 -> satisfiable by backpack/backupmanager[v4.0.0, v4.0.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require backpack/backupmanager:*" to figure out if any version is installable, or "composer require backpack/backupmanager:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Backpack, Laravel, PHP, DB version:
"php": "^7.3|^8.0",
"backpack/crud": "^5.5",

**Comment by jorgetwgroup** [comment]
Hi @mcfaith9 

The problem that you are facing seems to be related to the version incompatibility of the packages in your Laravel project.

The package "backpack/backupmanager" version ^4.0 requires the package "spatie/laravel-backup" version ^8.0. However, "spatie/laravel-backup" version ^8.0 requires the "illuminate/console" package version ^9.0, which conflicts with other dependencies in your project.

To resolve this issue, you can try the following steps:

1. Update the "composer.json" file in your project by changing the version requirement for "backpack/backupmanager" to a compatible version that supports "spatie/laravel-backup" version ^8.0. For example, you can change it to "^3.6" or an earlier compatible version.
2. Run the following command to update your composer dependencies: `composer update` (This should install the compatible versions of the packages and resolve the conflict.)
3. If the above step does not work, you can try running the following command to install the specific version of the "spatie/laravel-backup" package that is compatible with your Laravel version.

Therefore, to better assist you, please provide us with the following information:

- What version of Laravel are you using in your project?
- What version of PHP are you using in your environment?

This information can help us to provide a more accurate and specific solution to the version compatibility issue that you are facing.

**Comment by buliyo** [comment]
Same problem with latest XAMPP and PHP 8.2 and Laravel 10.5

**Comment by jorgetwgroup** [comment]
Hello @mcfaith9 and @buliyo 

I try this package in a clean install of Laravel 9 and Laravel 10, both work normally.

<img width="1013" alt="Screenshot 2023-04-12 at 08 57 20" src="https://user-images.githubusercontent.com/44643608/231464676-a47effd0-d01f-485d-a345-c48e8b5fba0a.png">

<img width="1019" alt="Screenshot 2023-04-12 at 08 58 47" src="https://user-images.githubusercontent.com/44643608/231464775-d22f69fd-0381-405f-8da2-7f7be20efeb6.png">

Could you try to give us more detail or screenshots of process.

Thanks.
