### ISSUE TITLE
Method formatLocalized does not exist.

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/BackupManager#124]
# Bug report

### What I did:

Create an application backup

### What I expected to happen:

Displays a list of backups

### What happened:

![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/c2f6b88e-444a-42c9-8a64-5fbda1ffc98e)

### What I've already tried to fix it:

The formatLocalized function is marked as **deprecated** and has been **removed** as of _Laravel 11_
```php
    public function index()
    {
     ...
         // only take the zip files into account
         if (str_ends_with($file, '.zip') && $disk->exists($file)) {
               $backups[] = (object)[
               ...
              \\ From:  'lastModified' => Carbon::createFromTimeStamp($disk->lastModified($file))->formatLocalized('%d %B %Y, %H:%M'),
              \\ To:    'lastModified' => Carbon::createFromTimeStamp($disk->lastModified($file))->isoFormat(config('backpack.ui.default_datetime_format')),
               ...
               ];
         }
     ...
    }
```

### Backpack, Laravel, PHP, DB version:

![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/92d6c373-509f-44f2-ad64-5d6b6bd3bd49)

**Comment by pxpm** [comment]
Thanks again for one more bug report @tringuyenduc2903 🙏 

It's fixed in 5.0.1. 

Cheers
