### ISSUE TITLE
ladda not defined

### ISSUE THREAD

**Issue by sakanaproductions** [Laravel-Backpack/BackupManager#13]
When doing a fresh install of base and backup manager getting 404 on the following ladda files:
ladda-themeless.min.css, ladda.js, spin.js, ladda.js

**Comment by tabacitu** [comment]
Hmm... Are you installing it on Laravel 5.2 or 5.3?

**Comment by sakanaproductions** [comment]
5.3, I looked through the github for ladda, and didn't see any code other than the link to the public directory

**Comment by tabacitu** [comment]
...I still can't find where those files are loaded. I remember I've removed them a long time ago.

Could you please help out with a screenshot of the url, page and error?

**Comment by sakanaproductions** [comment]
`vagrant@homestead:~/Code/actortracking.com/vendor/backpack/backupmanager$ grep "ladda" * -r
src/resources/views/backup.blade.php:    <link href="{{ asset('vendor/backpack/ladda/ladda-themeless.min.css') }}" rel="stylesheet" type="text/css" />
src/resources/views/backup.blade.php:      <button id="create-new-backup-button" href="{{ url(config('backpack.base.route_prefix', 'admin').'/backup/create') }}" class="btn btn-primary ladda-button" data-style="zoom-in"><span class="ladd-label"><i class="fa fa-plus"></i> {{ trans('backpack::backup.create_a_new_backup') }}</span></button>
src/resources/views/backup.blade.php:    <script src="{{ asset('vendor/backpack/ladda/spin.js') }}"></script>
src/resources/views/backup.blade.php:    <script src="{{ asset('vendor/backpack/ladda/ladda.js') }}"></script>
src/resources/views/backup.blade.php:        // Create a new instance of ladda for the specified button
`

**Comment by tabacitu** [comment]
Oh! I am so sorry, so stupid of me. I did not see this issue is posted in the BackupManager repository :-) I kept trying it for CRUD.

Oh, ok then, the ladda files should have been published when you installed Backpack\CRUD, in step 3, when you've run ```php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="public"```. Run it again to see if it fixes it.

If you haven't installed Backpack\CRUD at all because you don't need it, I've just pushed an update to Backpack\Base to include the ladda buttons there too. So after a ```composer update``` you should be able to run ```php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider"``` and the package will place the ladda buttons css and js in the proper folder.

Please tell me if this fixes it for you.

Cheers!

**Comment by sakanaproductions** [comment]
That fixed it, not sure why it didn't work the first time.  Thanks!
ᐧ

-------------------------------------------
Jamie Fishback
(323)393-3474
jamie@jamiefishback.com
http://www.jamiefishback.com

This e-mail message is for the sole use of the intended recipient(s) and
may contain confidential and privileged information.   Any unauthorized
review, use, disclosure or distribution is prohibited. If you are not
the intended recipient, please contact  the sender by reply e-mail and
destroy all copies of the original message.      Thank You.

On Mon, Oct 31, 2016 at 9:56 PM, Cristian Tabacitu <notifications@github.com

**Comment by tabacitu** [comment]
:-) ok, cheers!
