### ISSUE TITLE
Dropbox connection

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/BackupManager#14]
Any chance for a tutorial on connecting dropbox to backpack in order to backup on dropbox also the posibility of accessing the backups from elfinder?

I think i missing something from the start when i set the dropbox disk in the filesystem config file.

**Comment by deslittle** [comment]
I also couldn't get the Dropbox flysystem adaptor to work. Looking at the issues in the dropbox flysystem package I found this, [https://github.com/thephpleague/flysystem-dropbox/issues/14](https://github.com/thephpleague/flysystem-dropbox/issues/14).

Looks like the Dropbox v1 API is about to be deprecated.

**Comment by lloy0076** [comment]
@AurelDragut - a PR is most welcome but unless someone yells, getting flysystem adapter's to work isn't really part of Backpack (unless something Backpack is getting in the way).
