### ISSUE TITLE
Can this be installed with laravel 5.1?

### ISSUE THREAD

**Issue by mjk0621** [Laravel-Backpack/BackupManager#17]

**Comment by tabacitu** [comment]
Hi @mjk0621 ,

Unfortunately, no. Only Laravel 5.3 is supported, and limited features are available for Laravel 5.2. My recommendation is to upgrade your app anyway, Laravel 5.4 is right around the corner. You could use [Laravel Shift](https://laravelshift.com/) to do it faster.

Cheers!
