### ISSUE TITLE
Typo in line 3 and 5 of BackupManager/src/app/Http/Controllers/BackupController.php

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/BackupManager#19]
I fond that these two lines are the same.

**Comment by OwenMelbz** [comment]
Can you please elaborate on your problem?

This is a bit like saying "my car is not working as expected" - what are you expecting it to work like? what is your actually problem, cant solve what we don't know :D

**Comment by tabacitu** [comment]
Fixed. Thanks guys.
