### ISSUE TITLE
Error while publishing vendor

### ISSUE THREAD

**Issue by folkevil** [Laravel-Backpack/BackupManager#2]
I got this error while publishing vendor, please check it (using laravel 5.1)
***
php artisan vendor:publish --provider="Backpack\BackupManager\BackupManagerServiceProvider"
PHP Fatal error:  Call to undefined function Backpack\BackupManager\resource_path() in \backend\vendor\backpack\backupmanager\src\BackupManagerServiceProvider.php on line 35

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined function Backpack\BackupManager\resource_path()
***
with laravel 5.2 i got error:

ErrorException in FileViewFinder.php line 112:
No hint path defined for [backpack]. (View: vendor\backpack\backupmanager\src\resources\views\backup.blade.php)

**Comment by tabacitu** [comment]
Hi @folkevil ,

Very sorry for the late reply - I don't know how your issue slipped past me.
This has been long solved, though, so I'll go ahead and close the issue.

Cheers!

**Comment by tabacitu** [comment]
(please let me know if you get it again)
