### ISSUE TITLE
"'Controller' not found" when the project namespace has been customized

### ISSUE THREAD

**Issue by gergelykralik** [Laravel-Backpack/BackupManager#22]
Hi,

Steps to reproduce the problem:
set custom namespaci via `php artisan app:name`

Possible solution:
Extendt the default controller in `BackupController`
changing the use statement in said contoller
from:
```
use App\Http\Controllers\Controller;
```
to:
```
use Illuminate\Routing\Controller;
```

**Comment by OwenMelbz** [comment]
I have no contribution to make in this apart from a laracast and tweet conversation I read the other day where people regretted the invention of `app:name` as it causes so many issues xD wish I could find the thread.

I think more people would use the application controller than the vendor version.

For majority of users keeping it the same is best for them? But maybe provide documentation on suggestions how to adjust it. or some config.. maybe @tabacitu got ideas?

**Comment by gergelykralik** [comment]
Take a look at the code in the `\app\Http\Controllers\Controller` class, you will find this:

```php
use Illuminate\Routing\Controller as BaseController;
[...]
class Controller extends BaseController
[...]
```
I think you can extend the parent controller (`Illuminate\Routing\Controller`) and define the traits defined in the original `\app\Http\Controllers\Controller`.

like this:

```php
namespace Backpack\BackupManager\app\Http\Controllers;

use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Artisan;
use Log;
use Storage;

class BackupController extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    [...]
```

Another approach can be extracting the `Controller` class like this:

```php
namespace Backpack\BackupManager\app\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}
```

then extend this class from the `BackupController`, like this:

```php
namespace Backpack\BackupManager\app\Http\Controllers;

use Backpack\BackupManager\app\Http\Controllers\Controller;
[...]
class BackupController extends Controller
[...]
```

**Comment by tabacitu** [comment]
Hi @gergelykralik ,

Done! A ```composer update``` should fix it for you.

Cheers!
