### ISSUE TITLE
Error using the filesystem and google drive

### ISSUE THREAD

**Issue by joaomantovani** [Laravel-Backpack/BackupManager#23]
Hello, I've made a custom file-system which uses google drive and it's working

I've made this test: 
`Storage::disk('backups')->put('test.txt', 'Hello World');` 
and the file were successfully uploaded to the drive.

But when I tried to do a backup with this filesystem, He gave me this output:

```
$ php artisan backup:run 
Starting backup...
Dumping database mydesign...
Determining files to backup...
Zipped 1 files...
Copying 2017-02-22-125254.zip (size: 5.75 KB) to disk named backups...
Copying .zip file failed because: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: http---localhost.",
    "locationType": "parameter",
    "location": "fileId"
   }
  ],
  "code": 404,
  "message": "File not found: http---localhost."
 }
}
.
Backup completed!
```

So, the filesystem is working but not with backup, is it a bug?

**Comment by tabacitu** [comment]
Hm.... I guess this is more of an issue with [spatie/laravel-backup](https://github.com/spatie/laravel-backup). This is just an interface for it, and it looks to me like you've run their command directly in the command line.

So I'll close the issue, but **I'm very interested if you've managed to fixed this (and how)**. Is there something more we (or they) need to document for Google Drive backups?

Thanks, cheers!
