### ISSUE TITLE
Install problem, getting a 404

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/BackupManager#26]
I've followed all the steps but i keep getting a 404 for my_project_domain/admin/backup
I've installed others packages without any problems ("Base" of course, "CRUD" and "PermissionManager").

Here is the steps i did:

1 - composer require backpack/backupmanager

2 - in config/app.php 
```
Spatie\Backup\BackupServiceProvider::class,
Backpack\BackupManager\BackupManagerServiceProvider::class,
```
3 - php artisan vendor:publish --provider="Backpack\BackupManager\BackupManagerServiceProvider"

4 - in config/filesystems.php
```
// used for Backpack/BackupManager
'backups' => [
     'driver' => 'local',
     'root'   => storage_path('backups'), // that's where your backups are stored by default: storage/backups
],
```

Note: I've noticed i don't have the config/laravel-backup.php file.
I don't have any errors in my logs.

**Comment by adbmdp** [comment]
I can't find the solution.
I still have a 404. 
In /vendor/backpack/backupmanager/src/BackupManagerServiceProvider.php there is:
```
public function setupRoutes(Router $router)
{
      $router->group(['namespace' => 'Backpack\BackupManager\app\Http\Controllers'], function ($router) {
         require __DIR__.'/app/Http/routes.php';
        });
}
```

And in /vendor/backpack/backupmanager/src/app/Http/routes.php
```
<?php

Route::group(['prefix' => config('backpack.base.route_prefix', 'admin'), 'middleware' => ['web', 'auth']], function () {

    // Backup
    Route::get('backup', 'BackupController@index');
    Route::put('backup/create', 'BackupController@create');
    Route::get('backup/download/{file_name?}', 'BackupController@download');
    Route::delete('backup/delete/{file_name?}', 'BackupController@delete')->where('file_name', '(.*)');
});

```

Am I missing something ?

**Comment by adbmdp** [comment]
I finally get it to work.
Maybe it can help someone.
I had to do:

```
php artisan config:cache
php artisan cache:clear
```

**Comment by tabacitu** [comment]
Hi @adbmdp,

Sorry for taking so long to see this. Glad you figured it out, thank you for sharing your solution for others.

Cheers!
