### ISSUE TITLE
Guys you have to do something about src/app/Http/Controllers/BackupController.php#L5

### ISSUE THREAD

**Issue by juslintek** [Laravel-Backpack/BackupManager#27]
I'm really angry at this line, really! Like so angry that my butthole became a flame thrower! 
If I rename my app via artisan debug start swearing some inaccurate stack traces and that it cannot find that App\Http\Controllers\Controller; anymore 😡 Can you please resolve it somehow?

https://github.com/Laravel-Backpack/BackupManager/blob/master/src/app/Http/Controllers/BackupController.php#L5

Thank you for your audience.

![Approved](https://media.giphy.com/media/26gsvAm8UPaczzXz2/giphy.gif)

**Comment by lagbox** [comment]
https://github.com/Laravel-Backpack/BackupManager/issues/22 as well

**Comment by tabacitu** [comment]
Hi @juslintek ,

Will do, thank you. You're totally right, it should use the namespace.
Thanks for bringing this up and joking about it despite your frustration :-)

Any idea how we could fix it? I know we can use ```app()->getNamespace()``` inside a method to get the namespace, but we won't be able to use it when extending the Controller. We basically have to extend a controller whose namespace we don't know.

Cheers!

**Comment by juslintek** [comment]
I would do it like this:
```
...
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
...
class BackupController extends BaseController
{

use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
...
```

But if extending the app Controller is a must, than use direct approach by requiring controller from directory.

require dirname(__FILE__, 7) . 'app/Http/Controllers/Controller.php'; //With number 7 i might be wrong, I've counted that the depth of BackupController.php is 7 level deeper then web-root.

**Comment by tabacitu** [comment]
Hi @juslintek ,

Thanks for the tips. It seems like @chancezeus has done a very good job at fixing this problem already, by extending ```Illuminate\Routing\Controller```. I've just merged his work - it works flawlessly.

A ```composer update``` should fix it for you.

Cheers!
