### ISSUE TITLE
Mysqldump path on windows with spaces fails

### ISSUE THREAD

**Issue by DelightedD0D** [Laravel-Backpack/BackupManager#34]
I have this working great on my mac, but on my windows machine, the backups fail with the error

>error: Failed to backup because: The dump process failed with exitcode 1 : General error : 'C:\Program' is not recognized as an internal or external command,

The path to mysqldump is `C:\Program Files\MySQL\MySQL Server 5.7\bin` , note the spaces.

It seems those spaces are not being escaped int the command.

I have tried escaping my path, but I get the same error still:

DB_MYSQLDUMP_PATH 'C:\Program Files\MySQL\MySQL Server 5.7\bin'
DB_MYSQLDUMP_PATH "C:\Program Files\MySQL\MySQL Server 5.7\bin"
DB_MYSQLDUMP_PATH '"C:\Program Files\MySQL\MySQL Server 5.7\bin"'
DB_MYSQLDUMP_PATH C:\Program^ Files\MySQL\MySQL^ Server 5.7\bin

**Comment by DelightedD0D** [comment]
Ok, I was able to escape the spaces like this:

`DB_MYSQLDUMP_PATH "C:\Program^ Files\MySQL\MySQL^ Server^ 5.7\bin"`

That process might be worth a mention in the docs for those forced to use windows (surely against their will)

However, now I am getting: 

>error: Failed to backup because: The dump process failed with exitcode 7 : Unknown error : mysqldump: [ERROR] unknown variable 'defaults-extra-file=C:\Windows\Temp\php9D63.tmp'

**Comment by tabacitu** [comment]
:-)) @DelightedD0D , have you reached a solution for making backups on Windows, in the end? Would love to document it if you have one.

Cheers!

**Comment by DelightedD0D** [comment]
Not yet no. For now I just wrote a batch script and automated it with windows task scheduler to back up all my data till I have time to dig deeper into the issue here. Ill make sure to get back to you once I ve had a chance to work it through. :)

**Comment by tabacitu** [comment]
Ok, thank, cheers!
