### ISSUE TITLE
Slack Notifications: Where to put webhook URL

### ISSUE THREAD

**Issue by ompmega** [Laravel-Backpack/BackupManager#37]
Hi

I'm trying to send slack notifications after a backup is created, but I can't find where to put the webhook URL for Slack. It's not in the config file either.

Webhook URL: `https://hooks.slack.com/services/XXXXXX/XXXXXX`

I even tried looking for it within the `maknz/slack` parent package, but no luck... :(

Thanks!

**Comment by tabacitu** [comment]
I think you're looking for ```config/laravel-backup.php```.

Hope it helps. Cheers!
