### ISSUE TITLE
[Windows] Backup failed because The dump process failed with exitcode 1

### ISSUE THREAD

**Issue by fanybook** [Laravel-Backpack/BackupManager#38]
please update the "spatie/laravel-backup" package.

@see https://github.com/spatie/laravel-backup/issues/370

**Comment by tabacitu** [comment]
Hi @fanybook ,

Just pushed the upgrade to spatie/backup v4. You can upgrade using [the process outlined here](https://github.com/Laravel-Backpack/BackupManager#upgrading-from-11x-to-12x), it's really simple.

Hope it helps.
Cheers!
