### ISSUE TITLE
Update minimum requirement to PHP 7.0 & L5.5

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/BackupManager#42]
https://github.com/spatie/laravel-backup

This package requires PHP 7 and Laravel 5.5 or higher and so should we in order to stay compatible, now more so that 5.5 is LTS.

Maybe also point out in the readme that backupmanager 1.2 works for older versions of Laravel & PHP, and that 1.2.x+ is for older versions and 1.3+ works only on L5.5 & PHP7.0+ . (provided that 1.3 will be released as a consequence of this issue).

**Comment by CHOMNANP** [comment]
Have similar issue:
composer require backpack/backupmanager
Using version ^1.2 for backpack/backupmanager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for backpack/backupmanager ^1.2 -> satisfiable by backpack/backupmanager[1.2.0].
    - Conclusion: remove laravel/framework v5.5.13
    - Conclusion: don't install laravel/framework v5.5.13
    - backpack/backupmanager 1.2.0 requires spatie/laravel-backup ^4.19 -> satisfiable by spatie/laravel-backup[4.19.0, 4.19.1, 4.19.2].
    - spatie/laravel-backup 4.19.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.19.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.19.2 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/notifications v5.4.0|don't install laravel/framework v5.5.13
    - don't install illuminate/notifications v5.4.13|don't install laravel/framework v5.5.13
    - don't install illuminate/notifications v5.4.17|don't install laravel/framework v5.5.13
    - don't install illuminate/notifications v5.4.19|don't install laravel/framework v5.5.13
    - don't install illuminate/notifications v5.4.27|don't install laravel/framework v5.5.13
    - don't install illuminate/notifications v5.4.36|don't install laravel/framework v5.5.13
    - don't install illuminate/notifications v5.4.9|don't install laravel/framework v5.5.13
    - Installation request for laravel/framework 5.5.13 -> satisfiable by laravel/framework[v5.5.13].


Installation failed, reverting ./composer.json to its original content.

**Comment by gotrecillo** [comment]
Yeah +1 on this. Right now I am making a  CLI application to install laravel with backpack and add some packages.

At the moment I have  to disable the possibility to install this package.

**Comment by tabacitu** [comment]
Done! Thanks for the PR @cristianuibar . It's now merged, fixed and public as version 1.3.x

Check out the [upgrade steps](https://github.com/Laravel-Backpack/BackupManager#upgrading-from-12x-to-13x) or the [installation steps](https://github.com/Laravel-Backpack/BackupManager#install) (same as before).

Cheers!
