### ISSUE TITLE
getting 404 on /admin/backup

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/BackupManager#43]
Hi,
Ive followed all the installation steps.. for laravel 5.5 i used @dev branch.. but when i try to goto backup page.. im getting 404 page..
any solution?

**Comment by tabacitu** [comment]
Done! 

Backpack\BackupManager 1.3.x now supports L5.5. Check out the [upgrade steps](https://github.com/Laravel-Backpack/BackupManager#upgrading-from-12x-to-13x) or the [installation steps](https://github.com/Laravel-Backpack/BackupManager#install) (same as before).

Cheers!
