### ISSUE TITLE
Installation on L5.5.17 fails 

### ISSUE THREAD

**Issue by 1298799999** [Laravel-Backpack/BackupManager#44]
$ composer require backpack/backupmanager
```
Using version ^1.2 for backpack/backupmanager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for backpack/backupmanager ^1.2 -> satisfiable by backpack/backupmanager[1.2.0].
    - Conclusion: remove laravel/framework v5.5.17
    - Conclusion: don't install laravel/framework v5.5.17
    - backpack/backupmanager 1.2.0 requires spatie/laravel-backup ^4.19 -> satisfiable by spatie/laravel-backup[4.19.0, 4.19.1, 4.19.2].
    - spatie/laravel-backup 4.19.0 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.19.1 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - spatie/laravel-backup 4.19.2 requires illuminate/notifications ~5.3.28|~5.4.0 -> satisfiable by illuminate/notifications[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/notifications v5.4.0|don't install laravel/framework v5.5.17
    - don't install illuminate/notifications v5.4.13|don't install laravel/framework v5.5.17
    - don't install illuminate/notifications v5.4.17|don't install laravel/framework v5.5.17
    - don't install illuminate/notifications v5.4.19|don't install laravel/framework v5.5.17
    - don't install illuminate/notifications v5.4.27|don't install laravel/framework v5.5.17
    - don't install illuminate/notifications v5.4.36|don't install laravel/framework v5.5.17
    - don't install illuminate/notifications v5.4.9|don't install laravel/framework v5.5.17
    - Installation request for laravel/framework (locked at v5.5.17, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.17].


Installation failed, reverting ./composer.json to its original content.

```

**Comment by o15a3d4l11s2** [comment]
I have a similar issue with Laravel 5.5.18. Did you find any solution?

**Comment by OmarAlesharie** [comment]
I'm using Laravel 5.5.19 and facing the same issue?

**Comment by yclaes** [comment]
Same issues, using Laravel 5.5.20

**Comment by paulvl** [comment]
Same here

**Comment by dev** [comment]
Same here.

**Comment by kilrizzy** [comment]
Same issue, this look like it's because spatie/laravel-backup v4.19 only runs up to Laravel 5.4. Version v5+ would be needed to support Laravel 5.5+

**Comment by tabacitu** [comment]
Done! 

Backpack\BackupManager 1.3.x now supports L5.5. Check out the [upgrade steps](https://github.com/Laravel-Backpack/BackupManager#upgrading-from-12x-to-13x) or the [installation steps](https://github.com/Laravel-Backpack/BackupManager#install) (same as before).

Cheers!

**Comment by Abdul-Wahid12345** [comment]
Problem 1
   - Installation request for spatie/laravel-backup (locked at 6.0.5, required
s ^6.0) -> satisfiable by spatie/laravel-backup[6.0.5].
   - backpack/backupmanager 1.4.0 requires spatie/laravel-backup ^5.0 -> satisf
able by spatie/laravel-backup[v5.x-dev].
   - backpack/backupmanager 1.4.1 requires spatie/laravel-backup ^5.0 -> satisf
able by spatie/laravel-backup[v5.x-dev].
   - backpack/backupmanager 1.4.2 requires spatie/laravel-backup ^5.0 -> satisf
able by spatie/laravel-backup[v5.x-dev].
   - backpack/backupmanager 1.4.3 requires spatie/laravel-backup ^5.0 -> satisf
able by spatie/laravel-backup[v5.x-dev].
   - backpack/backupmanager 1.4.4 requires spatie/laravel-backup ^5.0 -> satisf
able by spatie/laravel-backup[v5.x-dev].
   - backpack/backupmanager 1.4.5 requires spatie/laravel-backup ^5.0 -> satisf
able by spatie/laravel-backup[v5.x-dev].
   - Conclusion: don't install spatie/laravel-backup v5.x-dev
   - Installation request for backpack/backupmanager ^1.4 -> satisfiable by bac
pack/backupmanager[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5].

help me, i am facing the same issue

**Comment by Abdul-Wahid12345** [comment]
when i'm trying to install the backupmanager package for my backpack dashboard,  by this command:
# Install the package
composer require backpack/backupmanager

the list of error's appears. Could you please help me to solve this issue.  Thanks in advanced

**Comment by tabacitu** [comment]
@Abdul-Wahid12345 what's your laravel version? Please run ```php artisan backpack:base:version``` and paste the output here.

**Comment by Abdul-Wahid12345** [comment]
C:\xampp\htdocs\gmzforexAgain>php artisan backpack:base:version
### PHP VERSION:
PHP 7.2.9 (cli) (built: Aug 15 2018 23:29:19) ( ZTS MSVC15 (Visual C++ 2017) x86
 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### BACKPACK PACKAGES VERSION:
'grep' is not recognized as an internal or external command,
operable program or batch file.


   Symfony\Component\Process\Exception\ProcessFailedException  : The command "co
mposer show | grep "backpack\|laravel/framework"" failed.

Exit Code: 255(Unknown error)

Working directory: C:\xampp\htdocs\gmzforexAgain

Output:
================


Error Output:
================
'grep' is not recognized as an internal or external command,
operable program or batch file.


  at C:\xampp\htdocs\gmzforexAgain\vendor\backpack\base\src\app\Console\Commands
\Version.php:72
    68|         });
    69|
    70|         // executes after the command finishes
    71|         if (!$process->isSuccessful()) {
  > 72|             throw new ProcessFailedException($process);
    73|         }
    74|     }
    75| }
    76|

  Exception trace:

  1   Backpack\Base\app\Console\Commands\Version::runCommand("composer show | gr
ep "backpack\|laravel/framework"")
      C:\xampp\htdocs\gmzforexAgain\vendor\backpack\base\src\app\Console\Command
s\Version.php:46

  2   Backpack\Base\app\Console\Commands\Version::handle()
      C:\xampp\htdocs\gmzforexAgain\vendor\laravel\framework\src\Illuminate\Cont
ainer\BoundMethod.php:29

  Please use the argument -v to see more details

**Comment by Abdul-Wahid12345** [comment]
i saw from composer.json file :  "laravel/framework": "5.7.*",

**Comment by tabacitu** [comment]
Hmm... very weird @Abdul-Wahid12345 . I recommend you upgrade to Laravel 5.8 and Backpack 3.6 - these latest versions work 100% together with BackupManager, just tested it myself.

Sorry I couldn't be of more help.
Cheers!
