### ISSUE TITLE
Class admin not found error

### ISSUE THREAD

**Issue by olubunmi708** [Laravel-Backpack/BackupManager#46]
# Bug report
ReflectionException in Container.php line 749:
Class admin does not exist
### What I did:
Followed normal installation of backpack/backupmanager on existing laravel installation.
after running the command `vendor:publish`
i got a success response. going to the address /admin/backup triggers the above error
### What I expected to happen:
suppose to show the UI admin panel
### What happened:
Error instance thrown

**Comment by tabacitu** [comment]
Hi @olubunmi708 - are you sure the installation worked correctly (the console output was fine)?

Sounds to me like it didn't. Could you please check if you're having the same problem when installing the latest version (1.3.x), and running all the installation steps here: https://github.com/Laravel-Backpack/BackupManager#install

Cheers!

**Comment by olubunmi708** [comment]
Thanks. i'm grateful. i'll look into that and give it another try.

**Comment by AlexMcowkin** [comment]
the same problem on 5.5
**Class admin does not exist**

if I have admin pane like subdomain. How I can change route?
example: admin.site.com/backupmanager

**Comment by tabacitu** [comment]
@AlexMcowkin , that's odd, you _should_ have the admin middleware, it comes with Backpack\Base.

@AlexMcowkin , as far as I know [using subdomains is dead-simple in Laravel](https://laravel.com/docs/5.5/routing#route-group-sub-domain-routing). Just make sure all your route groups use this custom domain. That might mean having custom routes for all Backpack pacakges, unfortunately (```routes/backpack/base.php```, ```routes/backpack/backupmanager.php``` etc).

Cheers!

**Comment by ziming** [comment]
I got my own admin middleware that is not named admin. How do I overwrite it?

**Comment by AbbyJanke** [comment]
@zimig you are going to have to overwrite the routes file for this package by creating a backupmanager.php in your “routes/backpack” folder. If you copy the current file from the package you can just remove the “admin” middleware. same would go with all backpack packages

**Comment by swingywc** [comment]
I got this error also after completing the installation steps.
![image](https://user-images.githubusercontent.com/9659080/76736760-68de8d80-67a2-11ea-86f1-ca8b938cfec2.png)

And I try to replace 'admin' with 'backpack_middleware()' but this will have another error:
#### Call to undefined function backpack_middleware()
![image](https://user-images.githubusercontent.com/9659080/76737028-f9b56900-67a2-11ea-946d-9be83b4f2997.png)

Here is my `composer.json`:

    {
        "name": "laravel/laravel",
        "type": "project",
        "description": "The Laravel Framework.",
        "keywords": [
            "framework",
            "laravel"
        ],
        "license": "MIT",
        "require": {
            "php": "^7.2.5",
            "backpack/backupmanager": "^2.0",
            "backpack/crud": "4.0.*",
            "backpack/permissionmanager": "^5.0",
            "barryvdh/laravel-elfinder": "^0.4.5",
            "fideloper/proxy": "^4.2",
            "fruitcake/laravel-cors": "^1.0",
            "guzzlehttp/guzzle": "^6.3",
            "laravel/framework": "^7.0",
            "laravel/tinker": "^2.0",
            "laravel/ui": "^2.0"
        },
        "require-dev": {
            "backpack/generators": "^2.0",
            "facade/ignition": "^2.0",
            "fzaninotto/faker": "^1.9.1",
            "laracasts/generators": "^1.1",
            "mockery/mockery": "^1.3.1",
            "nunomaduro/collision": "^4.1",
            "phpunit/phpunit": "^8.5"
        },
        "config": {
            "optimize-autoloader": true,
            "preferred-install": "dist",
            "sort-packages": true
        },
        "extra": {
            "laravel": {
                "dont-discover": []
            }
        },
        "autoload": {
            "psr-4": {
                "App\\": "app/"
            },
            "classmap": [
                "database/seeds",
                "database/factories"
            ]
        },
        "autoload-dev": {
            "psr-4": {
                "Tests\\": "tests/"
            }
        },
        "minimum-stability": "dev",
        "prefer-stable": true,
        "scripts": {
            "post-autoload-dump": [
                "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
                "@php artisan package:discover --ansi"
            ],
            "post-root-package-install": [
                "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
            ],
            "post-create-project-cmd": [
                "@php artisan key:generate --ansi"
            ]
        }
    }

**Comment by swingywc** [comment]
> I got this error also after completing the installation steps.
> ![image](https://user-images.githubusercontent.com/9659080/76736760-68de8d80-67a2-11ea-86f1-ca8b938cfec2.png)
> 
> And I try to replace 'admin' with 'backpack_middleware()' but this will have another error:
> 
> #### Call to undefined function backpack_middleware()
> ![image](https://user-images.githubusercontent.com/9659080/76737028-f9b56900-67a2-11ea-946d-9be83b4f2997.png)
> 
> Here is my `composer.json`:
> 
> ```
> {
>     "name": "laravel/laravel",
>     "type": "project",
>     "description": "The Laravel Framework.",
>     "keywords": [
>         "framework",
>         "laravel"
>     ],
>     "license": "MIT",
>     "require": {
>         "php": "^7.2.5",
>         "backpack/backupmanager": "^2.0",
>         "backpack/crud": "4.0.*",
>         "backpack/permissionmanager": "^5.0",
>         "barryvdh/laravel-elfinder": "^0.4.5",
>         "fideloper/proxy": "^4.2",
>         "fruitcake/laravel-cors": "^1.0",
>         "guzzlehttp/guzzle": "^6.3",
>         "laravel/framework": "^7.0",
>         "laravel/tinker": "^2.0",
>         "laravel/ui": "^2.0"
>     },
>     "require-dev": {
>         "backpack/generators": "^2.0",
>         "facade/ignition": "^2.0",
>         "fzaninotto/faker": "^1.9.1",
>         "laracasts/generators": "^1.1",
>         "mockery/mockery": "^1.3.1",
>         "nunomaduro/collision": "^4.1",
>         "phpunit/phpunit": "^8.5"
>     },
>     "config": {
>         "optimize-autoloader": true,
>         "preferred-install": "dist",
>         "sort-packages": true
>     },
>     "extra": {
>         "laravel": {
>             "dont-discover": []
>         }
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "app/"
>         },
>         "classmap": [
>             "database/seeds",
>             "database/factories"
>         ]
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "minimum-stability": "dev",
>     "prefer-stable": true,
>     "scripts": {
>         "post-autoload-dump": [
>             "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
>             "@php artisan package:discover --ansi"
>         ],
>         "post-root-package-install": [
>             "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "@php artisan key:generate --ansi"
>         ]
>     }
> }
> ```


My bad... I have accidentally change the `middleware_key` in `config/backpack/base.php`
