### ISSUE TITLE
Slack webhook non functional

### ISSUE THREAD

**Issue by xHeinrich** [Laravel-Backpack/BackupManager#47]
# Bug report
Slack notifications non functional or not enough info provided to correctly get them working.
Copying .zip file failed because: Unresolvable dependency resolving [Parameter #0 [ <required> $endpoint ]] in class Maknz\Slack\Client.
Backup failed because Unresolvable dependency resolving [Parameter #0 [ <required> $endpoint ]] in class Maknz\Slack\Client.
Backup failed because: Unresolvable dependency resolving [Parameter #0 [ <required> $endpoint ]] in class Maknz\Slack\Client.
[Illuminate\Contracts\Container\BindingResolutionException]
Unresolvable dependency resolving [Parameter #0 [ <required> $endpoint ]] in class Maknz\Slack\Client

### What I did:
Attempt to use slack notifications in this package, added the maknz/slack package which is now deprecated.
![image](https://user-images.githubusercontent.com/7674587/32696858-c426e7a8-c7ce-11e7-8013-86c60229fc42.png)

### What I expected to happen:
For notifications to work

### What happened:
![image](https://user-images.githubusercontent.com/7674587/32696874-036627d0-c7cf-11e7-97a8-9b6c0d18c4ac.png)

### What I've already tried to fix it:
Install forks, update configs ect

### Backpack, Laravel, PHP, DB version:
latest, php 7.1, Server version: 5.7.19-0ubuntu0.16.04.1 (Ubuntu)

**Comment by xHeinrich** [comment]
Fixed this by using the following fork: https://github.com/cristianuibar/BackupManager
Updating the laravel-backup config file to backup.php and modifying the configuration inside notifications to the following:
```         'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],

        /*
         * Here you can specify the notifiable to which the notifications should be sent. The default
         * notifiable will use the variables specified in this config file.
         */
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,
```

**Comment by lloy0076** [comment]
I'd be inclined to say that it's the move from upstream `spatie/laravel-backpack` 4.19 to the ^5.0 series that's provided the fix here.

**Comment by tabacitu** [comment]
Done! 

Backpack\BackupManager 1.3.x now supports L5.5, thanks to @cristianuibar 's PR. Check out the [upgrade steps](https://github.com/Laravel-Backpack/BackupManager#upgrading-from-12x-to-13x) or the [installation steps](https://github.com/Laravel-Backpack/BackupManager#install) (same as before).

Cheers!
