### ISSUE TITLE
Backup failed because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect

### ISSUE THREAD

**Issue by OdaiTu** [Laravel-Backpack/BackupManager#55]
# Bug report
Backup failed because: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")" when trying to connect

### What I did:
install laravel backpack backup right and it works using command line php artisan backup:run
### What I expected to happen:
backup successfully from website 

### What happened:

error 

![image](https://user-images.githubusercontent.com/12837840/42942645-3c648d16-8b69-11e8-9e38-c9412d384eea.png)

### What I've already tried to fix it:

i check my config\backup.php
--disable notification set to true

### Backpack, Laravel, PHP, DB version:

backpack:  3.4, 
laravel : 5.6
php: 7.2
BD: mysql

**Comment by OdaiTu** [comment]
when i set the '--only-files' => true flag in config its works fine
but i need the database backup

**Comment by tabacitu** [comment]
Hi @OdaiTu sounds like a mysqldump error to me, not BackupManager nor spatie/laravel-backup:

```
exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2004: "Can't create TCP/IP socket (10106 "Unknown error")"
```

Haven't run into this myself, so I'm afraid I can't help debug it.

Sorry, cheers!

**Comment by shahmir811** [comment]
Got a solution.
Place your laravel application inside xamp(htdocs) or wamp

stop `php artisan serve`

then enter following in your browser 

localhost/My_APP_NAME/public
