### ISSUE TITLE
Tag Crud Generator

### ISSUE THREAD

**Issue by EskindirA** [Laravel-Backpack/BackupManager#56]
# **Bug report**

   ErrorException  : Undefined index:

  at C:\Users\Eskindir\Desktop\backpack\onepack\vendor\backpack\base\src\app\Console\Commands\AddCustomRouteContent.php:55
    51|
    52|             // insert the given code before the file's last line
    53|             $file_lines = explode(PHP_EOL, $old_file_content);
    54|             $end_line_number = $this->customRoutesFileEndLine($file_lines);
  > 55|             $file_lines[$end_line_number + 1] = $file_lines[$end_line_number];
    56|             $file_lines[$end_line_number] = '    '.$code;
    57|             $new_file_content = implode(PHP_EOL, $file_lines);
    58|
    59|             if ($disk->put($path, $new_file_content)) {
### **What I did**:
Create a new laravel project and pulled backpack, started running the tag example
run 
php artisan backpack:base:add-custom-route "CRUD::resource('tag', 'TagCrudController');"
### **What I expected to happen**:
For all the requests to be generated as well as the route
### What happened:
Custom route not included, only TagCrudController generated
### **Backpack, Laravel, PHP, DB version**:
backpack/base                         0.9.7              Laravel Backpack's base package, which offers admin aut...
backpack/crud                         3.4.30            Quickly build an admin interface for your Eloquent mode...
backpack/generators               1.2.3              Generate files for laravel projects

Php version 7.2.0
Laravel 5.6.34
Mysql 5.7.14

**Comment by EskindirA** [comment]
Manually updated custom routes file by adding the route
CRUD::resource('tag', 'TagCrudController');

And included name in the fillable fields

works now.

**Comment by tabacitu** [comment]
Thank you @EskindirA - that definitely should not be happening. In fact, we've just pushed a fix last week making it more difficult for that to happen on Windows - hope a ```composer update``` fixes it for you.

If you _do_ get that again, could you do us a favour to help us debug the issue, please:
1. copy-paste your ```/routes/backpack/custom.php``` file here;
2. go to ```vendor/backpack/base/src/app/Console/Commands/AddCustomRouteContent.php:88``` and do a ```dd($file_lines);```, then copy-paste it here, so we can see _why_ your system didn't find the last line of that file;

Thanks a lot, cheers!

**Comment by tabacitu** [comment]
(unfortunately, we can't do a general return at the end of the ```customRoutesFileEndLine()``` method, because it's possible it would put the route OUTSIDE the admin middleware by accident - and we really don't want anybody to accidentally do that)
