### ISSUE TITLE
error con dump

### ISSUE THREAD

**Issue by danteCortes** [Laravel-Backpack/BackupManager#60]
Creo que a tu repositorio le falta mucha documentación.

Que hago cuando me sale este error?

Backup failed because: The dump process failed with exitcode 1 : General error : "'" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

ya agregué la clave dump en la conección:
'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
            'dump' => [
                'dump_binary_path' => '/C:/Program Files/PostgreSQL/10/bin/',
                'use_single_transaction',
                'timeout' => 60 * 5,
            ]
        ],
espero puedas ayudarme.

**Comment by tabacitu** [comment]
Hi @danteCortes ,

Haven't used this to backup PosgreSQL myself. I'm afraid I can't help you.

But this is just an interface for https://github.com/spatie/laravel-backup . Check that the command-line backup works, like instructed in their documentation. If it does, so will the interface.

Cheers!
