### ISSUE TITLE
method DELETE is not allowed 

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/BackupManager#62]
Error jquery.min.js:2 
DELETE https://dev.badawards.com/admin/backup/delete/http---localhost/2019-02-05-16-44-20.zip?disk=backups 405 (Method Not Allowed)  when click delete button

**Comment by gumpon** [comment]
I use function base64_encode URL is work.

**Comment by swayoleg** [comment]
> I use function base64_encode URL is work.

Can you please tell me how exatly did you fix it ?
