### ISSUE TITLE
Backups by application doesn't work, only by command line

### ISSUE THREAD

**Issue by enniosousa** [Laravel-Backpack/BackupManager#64]
# Bug report
When I click on dashboard button to create a backup, it doesn't work. When run `php artisan backup:run` the backup is successfully created and listed on backups list on dashboard.

### What I did:
I check the method `create` in `BackupController`, you are using `Symfony\Component\Process\Process` to run the command `php artisan backup:run` and it is the problem.
I sugest call this artisan comand using `Illuminate\Support\Facades\Artisan` [documented here](https://laravel.com/docs/5.5/artisan#programmatically-executing-commands)

### What I expected to happen:
That the backup to be created

### What happened:
No backup is created

### What I've already tried to fix it:
I did a pull request #65 to fix it

### Backpack, Laravel, PHP, DB version:
"backpack/crud": "^3.6.0",
"backpack/backupmanager": "^1.3",
"laravel/framework": "5.8.*",
PHP 7.2.14

**Comment by tabacitu** [comment]
You're right, if you can't manually call ```php artisan``` then it won't work. That's not nice. Thanks a lot for the PR, just merged and tagged it, so a ```composer update``` should do it for you.

Cheers! Keep 'em coming.
