### ISSUE TITLE
[Breaking Change] Stop customizing spatie/laravel-backup config file

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/BackupManager#68]
Spatie seems to push breaking changes as non-breaking regularly, so we should maybe stop overwriting their config file and just use a different config file instead:

- [ ] publish ```backup.php``` config file using spatie's publish command (instead of the one in BackupManager)
- [ ] ```config/backpack/backupmanager.php``` could be:
```php
<?php

return [
    // What is being run when the admin clicks on the "Create a new backup" button
    // You can add flags to this like --onlydb --onlyfiles --only-to-disk=name-of-disk
    // Details here: https://docs.spatie.be/laravel-backup/v4/taking-backups/overview
    'artisan_command_on_button_click' => 'backup:run',
];
```

- [ ] remove default "backups" disk, since this is just an opinion; maybe just include a suggestion in the installation docs;
- [ ] (maybe) on new backup click instead of showing a loader that doesn't actually track progress, we can show a notification that "_The backup process has been initiated. It can take 1-15 minutes. Check back later._"; and maybe add an auto-refresh to the page every 5 minutes or so;

**Comment by pxpm** [comment]
Done in #102 . closing 👍

**Comment by azaricstefan** [comment]
Great decision guys! 🥳
