### ISSUE TITLE
Authorization denied?

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/BackupManager#71]
# Bug report

### What I did:
clicked in the backup button on admin panel. 
### What I expected to happen:
backup done
### What happened:
 [2019-09-25 16:28:24] Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
### What I've already tried to fix it:
I run the backup from commandline it works fine but it says send notification error
### Backpack, Laravel, PHP, DB version:
backpack ver 4 laravel 6, php 7.2.18 mariadb

**Comment by tabacitu** [comment]
@samuk190 I think I know what your problem is - your ```mail``` isn't configured correctly in your .ENV file. The spatie/laravel-backup package doesn't mention this on installation, but you need mail configured for it to work. You can use mailtrap.io on localhost.

Hope it helps.
Cheers!
