### ISSUE TITLE
Configurable max_execution_time, so that backup doesn't trigger exception on shared hosting

### ISSUE THREAD

**Issue by JeremyGuinn** [Laravel-Backpack/BackupManager#82]
# Bug report

### What happened:
On shared hosting, the provider has prevented modifying resource limits.

> Resource limits, e.g. memory (memory_limit, post_max_size, upload_max_filesize), runtime (max_execution_time, max_input_time) etc. MAY NOT be INCREASED or EXCEEDED.

`ErrorException: ini_set(): Tried to raise runtime beyond limit (600/300).`

A config or environment variable to specify this would be helpful.

**Comment by tabacitu** [comment]
Hmm... I don't think there's not much you can do in this case @JeremyGuinn ... other than changing the hosting provider, or asking them to _manually_ increase it - sometimes they do that.

Sorry, can't be of any help in this case.

PS. This is more related to https://github.com/spatie/laravel-backup than BackupManager - this is just an interface that triggers their command.

**Comment by JeremyGuinn** [comment]
Its alright, I can work around it by overriding the routes and using a custom controller to change the ini_set(..).

**Comment by JeremyGuinn** [comment]
FYI: the error is caused in your BackupController, not in spatie's library.
app\Controllers\BackupController.php
```
    public function create()
    {
        $message = 'success';

        try {
            ini_set('max_execution_time', 600);
            
            ....
```

**Comment by tabacitu** [comment]
Oooh... alright then, sorry for pointing you to them. Hmm.. maybe we should make this configurable then... so that people in your situation can easily change the value...

I'll reopen this so we take a look at it after we launch 4.1 - thanks!

**Comment by pxpm** [comment]
Hello @JeremyGuinn 

You are totally right, sorry for taking so much time to get back into this. 

I'v just submited PR #84 that should address this issue.

Wish you the best,
Pedro
