### ISSUE TITLE
Backup add-on installation fails

### ISSUE THREAD

**Issue by Benoit1980** [Laravel-Backpack/BackupManager#85]
Hello,

I am installing backpack for the first time with Laravel  8:
```
    "require": {
        "php": "^7.3|^8.0",
        "backpack/crud": "4.1.*",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5"
    },
    "require-dev": {
        "backpack/generators": "^3.1",
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^0.0.5",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
```

I am following your tutorial and ran this command:
```
composer require backpack/backupmanager
```

But keep having this error:

```
C:\laragon\www\backpack>composer require backpack/backupmanager
Using version ^3.0 for backpack/backupmanager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException

  Target [Spatie\Backup\Tasks\Cleanup\CleanupStrategy] is not instantiable while building [Spatie\Backup\Commands\CleanupCommand].

  at C:\laragon\www\backpack\vendor\laravel\framework\src\Illuminate\Container\Container.php:1038
    1034▕         } else {
    1035▕             $message = "Target [$concrete] is not instantiable.";
    1036▕         }
    1037▕
  ➜ 1038▕         throw new BindingResolutionException($message);
    1039▕     }
    1040▕
    1041▕     /**
    1042▕      * Throw an exception for an unresolvable primitive.

  1   C:\laragon\www\backpack\vendor\laravel\framework\src\Illuminate\Container\Container.php:839
      Illuminate\Container\Container::notInstantiable("Spatie\Backup\Tasks\Cleanup\CleanupStrategy")

  2   C:\laragon\www\backpack\vendor\laravel\framework\src\Illuminate\Container\Container.php:279
      Illuminate\Container\Container::build("Spatie\Backup\Tasks\Cleanup\CleanupStrategy")
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

Any idea why please?

Thank you.

**Comment by Benoit1980** [comment]
Thank you for the reply.
It was a fresh installation of Laravel 8. I had not touched anything apart from the DB connection in the .ENV file.

I think you meant "we're now 3 devs working on it every day" and not "we're **not** 3 devs working on it every day"  :-)

Will you ever review the backpack license pricing nor not please? As there are more technologies like infyom coming out free.
I understand you have to sell to survive but will you ever go in the quickadminpanel kind of price per license?

As you have people who develop large apps, others mid level(5 to 10k budget) and then others who have project averaging 250 to 1k USD.

Thanks.

**Comment by tabacitu** [comment]
> It was a fresh installation of Laravel 8. I had not touched anything apart from the DB connection in the .ENV file.

Oh that's weird then. What PHP version are you using? I see your composer.json has `^7.3|^8.0` so I don't know which one is the one with the problem.

> I think you meant "we're now 3 devs working on it every day" and not "we're not 3 devs working on it every day" :-)

Haha exactly.

> Will you ever review the backpack license pricing nor not please? As there are more technologies like infyom coming out free. 

We'll reevaluate the pricing when we launch the next paid version (10-12 months). Until then we're stuck with what we have right now. We're weighing different options - subscriptions, open-core, purchasing-power-parity etc. It's a tough one.

> I understand you have to sell to survive but will you ever go in the quickadminpanel kind of price per license?

We do have price-per-license - our Single-Project License (69 EUR) is exactly for that purpose, when you want to use Backpack for one project, and one project alone.

> As you have people who develop large apps, others mid level(5 to 10k budget) and then others who have project averaging 250 to 1k USD.

Yeah that's exactly it. It's tricky to serve different needs and different budgets with one pricing. Your concern, from what I understand, is that Backpack is too expensive for one-off projects? When you only want to build one small project?

**Comment by tabacitu** [comment]
Update - since we couldn't replicate this and nobody else has joined the conversation to confirm it... I'm going to assume it's been fixed or a one-off, so I'll close this issue.

@Benoit1980 if you get this again, please let us know and we'll reopen.

If anybody else stumbles onto this error, please let us know too, we'll reopen.

Cheers!
