### ISSUE TITLE
Backup failed in browser but it works with php artisan backup:run

### ISSUE THREAD

**Issue by JoseElizondoGuzman** [Laravel-Backpack/BackupManager#94]
# Bug report

### What I did:"Create a new backup"
What I expected to happen: Backup successfully done

### What I expected to happen:
Be able to create the backup
### What happened: I was not able to create the backup when i click on create
![image](https://user-images.githubusercontent.com/60201541/126081875-ffdfd793-3e41-4873-ab50-9f32bc2345a6.png)
and i get this error -> bundle.js?v=4.1.48@53bc6028f445f9b2ecfb8893283f6b6087539353:2 PUT http://127.0.0.1:8000/admin/backup/create 500 (Internal Server Error)

_Failed to authenticate on SMTP server with username "testBenefitsCenter@gmail.com" using 3 possible authenticators. Authenticator LOGIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials 67sm5788273qtf.83 - gsmtp ". Authenticator PLAIN returned Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials 67sm5788273qtf.83 - gsmtp ". Authenticator XOAUTH2 returned Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials 67sm5788273qtf.83 - gsmtp "._

### What I've already tried to fix it:
I had change some mail values in the .env and follow other steps, however i am getting this issue over the browser

### BACKPACK VERSION:
4.1.48@53bc6028f445f9b2ecfb8893283f6b6087539353
### PHP VERSION:
PHP 8.0.5 (cli) (built: Apr 28 2021 00:30:18) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
### LARAVEL VERSION:
v8.50.0@d892dbacbe3859cf9303ccda98ac8d782141d5ae
DB: MySql Workbench CE 8.0

**Comment by JoseElizondoGuzman** [comment]
Nevermind - this was some missconfiguration from my side! thanks in any case! :)

**Comment by tabacitu** [comment]
Thanks for the update @JoseElizondoGuzman . What in particular was misconfigured in your case? It might help others who run into the same problem.

**Comment by JoseElizondoGuzman** [comment]
It was actually an issue with the email configuration, i had to set up the email to enable external apps to access it, after that this issue got fixed.
_https://support.google.com/accounts/answer/3466521?hl=en#:~:text=Go%20to%20the%20Security%20section,service%20you%20want%20to%20review._
